spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    initialization-mode: always
    schema: schema.sql
    data: data.sql
    show-sql: true
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace