spring:
  messages:
    encoding: UTF-8
    basename: i18n.bundle
answer-scoring:
  rightAnswerMark: 10
  wrongAnswerMark: -20
  minimumMarkToCompleteTest: 20

common:
  locale: ru_RU

questions:
  basename: questions_<locale>.csv
